### ISSUE TITLE
The source code is published on npmjs.com, not the distribution

### ISSUE THREAD

**Issue by max-baz** [benoitzohar/cerebro-timestamp#1]
When you plugin is installed via Cerebro, it cannot be used, because you published source code on npmjs.com, not the distribution.

Cerebro is looking for a `dist` folder and loading `index.js` from it, but this folder is missing. I could workaround that by running `npm run build` after I downloaded your plugin, but that shouldn't be normally used.

Also there are lots of [debug] messages in console coming from your plugin, it would be nice if you stripped them out.

![image](https://cloud.githubusercontent.com/assets/1177900/23592074/b78ce7ac-01fb-11e7-8ca4-397601f31047.png)

**Comment by benoitzohar** [comment]
Thanks for the heads up! I fixed it on master and npmjs.
