### ISSUE TITLE
can it work without "ts"?

### ISSUE THREAD

**Issue by farfromrefug** [benoitzohar/cerebro-timestamp#3]
By any chance could it work like the calc?
I mean by just inputing ```1488570776213``` you could recognize it (simple regex) and then directly show the result in the list.

Would be so much better!

Thanks

**Comment by benoitzohar** [comment]
Great idea!

I just enabled this (only for unix times though) in v0.2.1.

You can now type directly a number of seconds or milliseconds since epoch.

Thanks!

**Comment by farfromrefug** [comment]
@benoitzohar it works great ! 

Awesome update!. Just that could make me use cerebro as my main launcher!
