### ISSUE TITLE
Feature request: add support for unix nanoseconds timestamp

### ISSUE THREAD

**Issue by max-baz** [benoitzohar/cerebro-timestamp#4]
I've been working with unix timestamps a lot recently, and quite a few tools use nanoseconds precision. It would be nice to add support for unix nanoseconds timestamp directly.

You could add microseconds as well for completeness, but honestly I haven't seen microseconds being used anywhere.

**Comment by max-baz** [comment]
Hey @benoitzohar, I've had a few feature ideas in mind that I want to implement, including this one. Do you still use Cerebro and/or do you have time maintaining this project (merging PRs, releasing new versions)? If not, I can take over this project if you want and just do it myself. I want to avoid publishing a duplicate package on npmjs if possible 🙂

I have experience already with [cerebro-pass](https://github.com/maximbaz/cerebro-pass/issues/8) :stuck_out_tongue_winking_eye:

**Comment by benoitzohar** [comment]
Hey! Sorry for the long answer, that never left my todo list tbh!
You can do a PR 😉
Thanks!

**Comment by max-baz** [comment]
Glad to hear that you are still using it 😉.
Created #5 and #6.

**Comment by max-baz** [comment]
Thanks for merging so quickly, could you please also upload a new version to npmjs? 🙂

**Comment by benoitzohar** [comment]
Thanks for the PRs! I just published v0.3.0 to npmjs.
